name: Python CI

on:
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: install dependencies
      run: python -m pip install pytest
    - name: Run tests
      working-directory: exercise_2
      run: pytest


  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: install dependencies
      run: pip install flake8
    - name: Run tests
      working-directory: exercise_2
      run: flake8 .
