name: Docker CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      # Add more steps here
      - name: Login to dockerhub
        uses: docker/login-action@v3
        with: # Set the secret as an input
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ../exercise_3/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/clockbox:latest
  # More jobs can be added
